# Do not change this value manually.
# It is used by PocketDice to automatically update this file between versions.
config-version: 1
radius: 16
default_notation: "1d100"
max_dice: 50
max_faces: 1000
message_format: "&b[PocketDice]&r {player} rolled &e{notation}&r: &7{results}&r (total &a{total}&r)"
error_format: "&c[PocketDice]&r {message}"
allow_shorthand_d: true
